### ISSUE TITLE
Console logging

### ISSUE THREAD

**Issue by GiuliaTeggi** [fac-14/CGKO_API#25]
Just a tiny remark - it's best practice to remove commented out code and console logs from your master/production code. :wink:

**Comment by martingaston** [comment]
Here's some links if it's useful (yes I've just discovered that Github can do this so boy am I going to play with it) :muscle: 

https://github.com/fac-14/CGKO_API/blob/208f12c3998a19a995e392dd422a1d2ed4da108b/index.html#L7

https://github.com/fac-14/CGKO_API/blob/208f12c3998a19a995e392dd422a1d2ed4da108b/dom.js#L25

https://github.com/fac-14/CGKO_API/blob/208f12c3998a19a995e392dd422a1d2ed4da108b/dom.js#L29-L31

https://github.com/fac-14/CGKO_API/blob/208f12c3998a19a995e392dd422a1d2ed4da108b/dom.js#L45
