### ISSUE TITLE
Need for IIFFE?

### ISSUE THREAD

**Issue by GiuliaTeggi** [fac-14/CGKO_API#34]
I'd just like to point out something about IIFEs, given that you wrapped all of your functions inside one :relaxed: 

Immediately invoked function expressiosns are great to execute a function immediately after invoking it and to avoid polluting the global namespace - since all variable declared inside the IIFE are not accessible from the outside. 

In your case though, all the functions depend on event listeners (no function is called immediately as the javascript file is read) and there are no other variables or functions outside of the IIFE -
 which could have changed the values of the variables you have inside of it. 

Because of these reasons an IIFE wasn't necessary in your case - it's good to practice using them, given that you've just learnt about closures, but just make sure to understand which use cases are best suited to use them. :wink:

**Comment by Zeanort** [comment]
Thanks for the heads up, your right about the IFFE, we just used it initially to troubleshoot something but we see it's not necessary now. Thanks :)
